data:
  bronze_path: "data/bronze/Iris.csv"
  silver_path: "data/silver/Iris_clean.csv"
  gold_path: "data/gold/Iris_final.csv"

  train_path: "data/gold/Iris_train.csv"
  test_path: "data/gold/Iris_test.csv"

  drop_columns: ["Id"]
  selected_features: ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]


model:
  target: "species"
  test_size: 0.2
  random_state: 42
  output_path: "models/iris_model.pkl"